import XSS from 'xss'
import { IFilterXSSOptions } from 'xss'

const XSS_OPTIONS : IFilterXSSOptions = {
    css : {
        whiteList : {
            'color' : true,
            'background-color': true,
            'top' : true,
            'left' : true,
            'text-decoration-line' : true,
            'font-family' : true,
            'font-size' : true,
            'font-weight' : true,
            'border-collapse' : true,
            'width' : true,
            'height' : true,
            'border' : true,
            'position' : true,
            'overflow' : true,
            'clip' : true,
            'padding-left' : true,
            'padding-right' : true,
            'padding-top' : true,
            'padding-bottom' : true,
            'padding' : true,
            'background-image' : true,
            'background' : true,
            'margin' : true,
            'margin-left' : true,
            'margin-right' : true,
            'margin-top' : true,
            'margin-bottom' : true,
            'max-width' : true
        }
    },
    whiteList : {
        p : ['style','class'],
        h1 : ['style','class'],
        h2 : ['style','class'],
        h3 : ['style','class'],
        h4 : ['style','class'],
        h5 : ['style','class'],
        h6 : ['style','class'],
        span : ['style','class'],
        br : [],
        img : ['src','class','preview', 'style', 'contenteditable', 'width'],
        a : ['href','target'],
        sup : ['class'],
        ol : ['class'],
        li : ['class'],
        ul : ['class'],
        blockquote : ['class'],
        em : ['class'],
        s : ['class'],
        u : ['class'],
        strong : ['class'],
        pre : ['class','spellcheck'],
        font : ['class','size'],
        table : ['border','width','cellpadding','cellspacing','style'],
        tbody : [],
        tr : ['height'],
        th : [],
        td : ['class','width','colspan','rowspan','height'],
        div : ['style','class'],
        colgroup : [],
        col : ['width','span'],
        code : [],
        pmicrosoft : [],
        spanmicrosoft : [],
        latexpression : ['size'],
        blogpreview : ['pid'],
        b : [],
        small : [],
        big : [],
        mark : [],
        hr : [],
        article : [],
    }
}

export const xssFilter = (html : string) : string => {
    return XSS(html, XSS_OPTIONS)
}